### ISSUE TITLE
구성

### ISSUE THREAD

**Issue by khw7096** [75mm-studio/web2#1]
- 로고 + 메뉴바
     - 메뉴바에 Support, Estimate 넣을지 말지 고민하는 포인트가 있다.
- 릴: mp4(자동재생, 1080p, 720p): https://www.w3schools.com/howto/howto_css_fullscreen_video.asp
- 로고 + 회사소개
- 접근 아이콘: onset, matchmove, estimate
- 포스터: 페이지로 나눌것인지 맨 밑에 길게 할 것인지 체크하기. / 3개 테스트
    - https://getbootstrap.com/docs/5.0/examples/carousel/
    - https://getbootstrap.com/docs/5.0/components/carousel/ 한 슬라이드에 3개씩 배치해보기
    - https://blogpack.tistory.com/815: Custom 하게 만들 때
    - https://swiperjs.com: 요즘 핫한 슬라이드 라이브러리
- 리서치: 구글(O)로 테스트
    - https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=ndarkness75&logNo=221515796072
    - https://developers.google.com/maps/documentation/javascript/overview?hl=ko
    - http://developers.google.com/ 가입하기
    - https://lcw126.tistory.com/192
- Clients 추가?

**Comment by baesy0** [comment]
## 메인 페이지
### 릴 동영상 블럭(첫번째)
- 동영상은 자동재생
- 동영상 화면 크기
### 로고 및 세부 소개 블럭(두번째)
- 클릭하면 feature 페이지로 넘어가도록
- 블럭 세로길이 짧게
### ONSET / MM / ESTIMATE 버튼 블럭(세번째)
- 이미지형태의 버튼
- estimate의 UX 고민(사용자 입장에서의 직관성)
### 포스터(history) 블럭(네번째)
- 3개로
### contact 블럭(다섯번째)

**Comment by khw7096** [comment]
1차 구현 완료.
🍶
