### ISSUE TITLE
vimeo 영상 가운데 버튼 안나오게

### ISSUE THREAD

**Issue by baesy0** [75mm-studio/web2#34]

**Comment by khw7096** [comment]
UX 안나오게 처리하기 위해서 Vimeo 계정의 어드민 권한이 필요함.

**Comment by khw7096** [comment]
어드민 메뉴에서 스크린샷 받기

**Comment by baesy0** [comment]
### 동영상 플레이어 커스텀하기(Vimeo 공식 문서)
https://vimeo.zendesk.com/hc/ko/articles/224972808-동영상-플레이어-커스텀하기

**Comment by khw7096** [comment]
PD님이 참고로 보내준 사이트: https://hiizz.tistory.com/4
