### ISSUE TITLE
google map 가격정책

### ISSUE THREAD

**Issue by khw7096** [75mm-studio/web2#39]
URL: https://console.cloud.google.com/apis/library/maps-backend.googleapis.com?id=fd73ab50-9916-4cde-a0f6-dc8be0a0d425&project=lazypic-gmap

<img width="766" alt="image" src="https://user-images.githubusercontent.com/1149996/120959121-136e1200-c794-11eb-867e-5735d7becdfd.png">

**Comment by baesy0** [comment]
조사 완료! 🙌
