### ISSUE TITLE
상단 메뉴의 구조 데이터

### ISSUE THREAD

**Issue by khw7096** [75mm-studio/web2#42]
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/1149996/120972128-6225a700-c7a8-11eb-82b4-e0c3cdea2106.png">

**Comment by ejsim** [comment]
당장 중요한 사항은 아니지만, 서비스와, Estimate란에 *3D scan service -> Capture Solution 으로 바꿔주시면 감사하겠습니다.

**Comment by baesy0** [comment]
> 당장 중요한 사항은 아니지만, 서비스와 Estimate란에 *3D scan service -> Capture Solution 으로 바꿔주시면 감사하겠습니다.

넹 알겠습니다! 🙌

**Comment by khw7096** [comment]
오 깃허브에 오신것을 환영합니다. :-)
